// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYMhEHmRL9X0a171vUPJV1eKcNbtgNcoc',
    appId: '1:43604858069:web:7f759b4e2166332fee3e5c',
    messagingSenderId: '43604858069',
    projectId: 'pdfshit-3e06b',
    authDomain: 'pdfshit-3e06b.firebaseapp.com',
    storageBucket: 'pdfshit-3e06b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2u48k4Iw_xd47Rre3wjvW14vMNNJobvw',
    appId: '1:43604858069:android:3489c94e0a0e82a3ee3e5c',
    messagingSenderId: '43604858069',
    projectId: 'pdfshit-3e06b',
    storageBucket: 'pdfshit-3e06b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugHF_RbrwmcVLQstYmVw8NaGbMtVWf0I',
    appId: '1:43604858069:ios:2840918932346469ee3e5c',
    messagingSenderId: '43604858069',
    projectId: 'pdfshit-3e06b',
    storageBucket: 'pdfshit-3e06b.appspot.com',
    iosBundleId: 'com.example.pdfshits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugHF_RbrwmcVLQstYmVw8NaGbMtVWf0I',
    appId: '1:43604858069:ios:2840918932346469ee3e5c',
    messagingSenderId: '43604858069',
    projectId: 'pdfshit-3e06b',
    storageBucket: 'pdfshit-3e06b.appspot.com',
    iosBundleId: 'com.example.pdfshits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYMhEHmRL9X0a171vUPJV1eKcNbtgNcoc',
    appId: '1:43604858069:web:e59a2daa8596e005ee3e5c',
    messagingSenderId: '43604858069',
    projectId: 'pdfshit-3e06b',
    authDomain: 'pdfshit-3e06b.firebaseapp.com',
    storageBucket: 'pdfshit-3e06b.appspot.com',
  );
}
